dist: focal
language: ruby
rvm: 2.7.3

env:
  global:
  - PGUSER=postgres
  - PGPORT=5432
  - PGHOST=localhost
before_install:
- sudo apt install postgresql postgresql-contrib
- sudo service postgresql restart
- sleep 1
- postgres --version

script:
  - psql -c 'create database travis_ci_test;' -U postgres