dist: xenial
language: ruby
rvm: 2.7.3
services:
  - xvfb
  - postgresql

addons:
  postgresql: '13'
before_install:
- sudo service postgresql restart
- postgres --version

script:
- gem install rails
- gem install pg
- rails new test-project --database=postgresql
- cd test-project
- rails db:create
- rails g scaffold Test name:string
- rails db:migrate
- postgres --version