dist: focal
language: ruby

addons:
  postgresql: '13'
  apt:
      packages:
        - postgresql-13
#before_install:
#- postgres --version

script:
- gem install rails
- gem install pg
- rails new test-project --database=postgresql
- rails db:migrate
- postgres --version